version: '3.8'
services:
  db:
    image: postgres:14-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Pa$$w0rd
      POSTGRES_DB: backend_db
      POSTGRES_HOST_AUTH_METHOD: trust
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
