"""Update todo model

Revision ID: 20e13d98dd28
Revises: 05ad95fd9518
Create Date: 2023-04-11 14:42:00.525833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e13d98dd28'
down_revision = '05ad95fd9518'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.drop_index('ix_todos_id', table_name='todos')
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
