"""Add message_id to model todo

Revision ID: 9caf5ad62e19
Revises: 84787de59c6c
Create Date: 2023-04-13 16:23:06.322642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caf5ad62e19'
down_revision = '84787de59c6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_todos_message_id'), 'todos', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_message_id'), table_name='todos')
    op.drop_column('todos', 'message_id')
    # ### end Alembic commands ###
